### ISSUE TITLE
Cocoapods 0.39.0 errors

### ISSUE THREAD

**Issue by davidchiles** [ChatSecure/SignalProtocol-ObjC#1]
Encountered the problem using Cocoapods 0.39.0 on both the test project and ChatSecure-iOS.

XCode gives the following errors for `SignalContext.m`:

```
SignalContext.m:10:9: Use of private header from outside its module: 'SignalContext_Internal.h'
SignalContext.m:12:9: Use of private header from outside its module: 'SignalStorage_Internal.h'
```

Changes to ChatSecure-iOS Podfile:

``` ruby
pod 'SignalProtocolC', :podspec => 'https://raw.githubusercontent.com/ChatSecure/SignalProtocolC.podspec/3f30f3d50d1a85305df3ff5f047b3dd379f12e73/SignalProtocolC.podspec'
pod 'SignalProtocol-ObjC', :path => 'Submodules/SignalProtocol-ObjC/SignalProtocol-ObjC.podspec'
```

Since we still can't use Cocoapods 1.x.x with ChatSecure-iOS we should try to find a way to make this work on 0.39.0.

**Comment by chrisballinger** [comment]
Strange that it didnt show up in 1.x.x. I might want to take another stab at moving us to 1.x.x because I think at least some of the issues we had before have been fixed.

Does the same problem occur if you clone the SignalProtocol-ObjC repo and use CocoaPods 0.39 in the test project there?

**Comment by davidchiles** [comment]
Yes the error occurs in the test project too

**Comment by chrisballinger** [comment]
No longer using 0.39
