### ISSUE TITLE
Option to export SignalKeyPair as serialized data

### ISSUE THREAD

**Issue by Manbearpixel** [ChatSecure/SignalProtocol-ObjC#14]
Hello! I've been combing over this CocoaPod wrapper for the Signal Protocol library for Objective-C. It's a very interesting port so far!

One blocker I've hit is trying to serialize the `publicKey` and `privateKey` for a `SignalKeyPair` through this pod. Using the JAVA library I was able to call something like...

```
SignalKeyPair.getPublicKey().serialize()
```

Which I could then export as a base64, and import again elsewhere and load back in as a serialized data source.

Is this something not possible with this wrapper?

**Comment by chrisballinger** [comment]
You can use base64 serialization provided by NSData

**Comment by Manbearpixel** [comment]
Thanks! Found a solution there :)
