### ISSUE TITLE
Is it correct to call copy?

### ISSUE THREAD

**Issue by ma11hew28** [ChatSecure/SignalProtocol-ObjC#5]
Is this line correct?

https://github.com/ChatSecure/SignalProtocol-ObjC/blob/master/Classes/Models/SignalAddress.m#L26

Shouldn't it just be: `_name = name;`? Because, doesn't ARC take care of the reference counting for you?

**Comment by chrisballinger** [comment]
This is to cover the edge case where `name` is a mutable string, because otherwise bad things can happen if it's mutated later when we're not expecting it. If you pass in a real NSString the `copy` simply increases the reference count.

**Comment by ma11hew28** [comment]
Oh, right. OK. Thanks! :-)
